### ISSUE TITLE
docker-compose.yml environment is not working

### ISSUE THREAD

**Issue by tk50486yui** [tk50486yui/VueProject#2]
docker-compose.yml

```
version: '1.0'

services:
  vue-nginx:
    build:
      context: .
    ports:
      - "8088:80"
    environment:
      API_URL: http://localhost:4000
```
.env  `API_URL: http://localhost`

and run `docker-compose up -d`

but API_URL is not replace API_URL in  .env
